### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/.local'

### ISSUE THREAD

**Issue by imamhossain94** [imamhossain94/annex-server#1]
Error occurred when call this API,
https://annex-server-prod-annex-l4sa4h.mo6.mogenius.io/annex/v1/routine?type=image&phpsessid=8b0d6b4b7934e9fef2d4c8b9484*****

> [2022-12-27 03:54:39,125] ERROR in app: Exception on /annex/v1/routine [GET]
Traceback (most recent call last):
  File "/app/route.py", line 25, in routine
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/route.py", line 28, in routine
    return loop.run_until_complete(studentRoutine())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/v1/routine.py", line 90, in studentRoutine
    routine_image_url = await take_screenshot(file_name=fileName, url=routineUrl, phpsessid=phpsessid)
  File "/app/v1/helper/take_screenshot.py", line 13, in take_screenshot
    browser = await launch(handleSIGINT=False, handleSIGTERM=False, handleSIGHUP=False, args=args)
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 113, in __init__
    CHROME_PROFILE_PATH.mkdir(parents=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1292, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.local'

**Comment by imamhossain94** [comment]
Issue solved after deployed on render
